### ISSUE TITLE
name and names of children for gtable

### ISSUE THREAD

**Issue by kohske** [r-lib/gtable#19]
see this issue: https://github.com/wch/ggplot2/pull/3

**Comment by thomasp85** [comment]
We need to think about naming in general a lot. There are currently 4 names to consider. The name of the gtable, the 2 dimnames, and the names of the grobs. Currently the dimnames are correctly derived during construction but not touched further when the gtable is modified (e.g. with `gtable_add_rows()`. The grob-names are always updated but often simply derive from the gtable name which is not very useful.

It would make sense to add a `name` argument to every function that alters the dimensions of the table so that dimnames can get updated. if missing, and dimnames are set on the object it would default to `""` in line with how dimnames work in general.

For grob names it is a bit more complicated. The current, simply defaulting to the gtable name is not sensible IMO, but is of course easy. Using make.names could at least ensure uniqueness...
